# .pre-commit-config.yaml
default_stages: [commit]
repos:
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.76.0
      hooks:
          - id: terraform_checkov
          - id: infracost_breakdown
          - id: terraform_docs
          - id: terraform_fmt
          - id: terraform_providers_lock
          - id: terraform_validate
          - id: terraform_tflint
          - id: terraform_tfsec
          - id: terragrunt_fmt
          - id: terragrunt_validate
          - id: terrascan
          - id: tfupdate
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
