name: tfsec
on:
  workflow_dispatch:
  pull_request:
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: .
        config-file: .terraform-docs.yml
        output-file: README.md
        output-method: replace
        git-push: "true"